# Generated by Django 5.2.3 on 2025-06-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('TEC Upload', 'TEC Upload'), ('Host Upload', 'Host Upload'), ('Simulated TEC', 'Simulated TEC'), ('Tracker Generated', 'Tracker Generated')], max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
