# Generated by Django 5.2.3 on 2025-07-01 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Temperature_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='uploadlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='uploadlog',
            index=models.Index(fields=['timestamp'], name='Temperature_timesta_7aa20d_idx'),
        ),
    ]
