# Generated by Django 5.2.3 on 2025-07-01 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Temperature_app', '0002_alter_uploadlog_options_uploadlog_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Upload Log', 'verbose_name_plural': 'Upload Logs'},
        ),
    ]
