# Generated by Django 5.2.3 on 2025-07-01 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Temperature_app', '0003_alter_uploadlog_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadLog',
        ),
    ]
