# Generated by Django 5.2.3 on 2025-07-08 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Temperature_app', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
