# Generated by Django 5.2.3 on 2025-07-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Temperature_app', '0006_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
