# Generated by Django 5.1.4 on 2025-07-08 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Temperature_app', '0007_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
