# Generated by Django 5.2.3 on 2025-07-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Temperature_app', '0010_uploadlog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadlog',
            name='user',
        ),
    ]
