# Generated by Django 5.2.3 on 2025-07-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Temperature_app', '0011_remove_uploadlog_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='uploadlog',
            name='generated_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadlog',
            name='threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
