# Generated by Django 5.2.3 on 2025-07-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Temperature_app', '0012_alter_uploadlog_options_uploadlog_generated_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadlog',
            name='delete_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadlog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadlog',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadlog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
