# Generated by Django 5.2.3 on 2025-07-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Temperature_app', '0013_uploadlog_delete_reason_uploadlog_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadlog',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadlog',
            name='generated_file_content',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadlog',
            name='generated_file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadlog',
            name='original_file_content',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
