# Generated by Django 5.2.3 on 2025-07-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Temperature_app', '0014_uploadlog_file_size_uploadlog_generated_file_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadlog',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='uploadlog',
            name='generated_file_content',
        ),
        migrations.RemoveField(
            model_name='uploadlog',
            name='generated_file_size',
        ),
        migrations.RemoveField(
            model_name='uploadlog',
            name='original_file_content',
        ),
        migrations.AddField(
            model_name='customer',
            name='delete_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
