# Generated by Django 4.2.18 on 2025-08-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Temperature_app', '0015_remove_uploadlog_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='default_threshold',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_tracker_generated',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
