# Generated by Django 4.2.18 on 2025-08-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Temperature_app', '0016_customer_default_threshold_and_more'),
    ]

    operations = [
    ]
