# Generated by Django 4.2.18 on 2025-08-07 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Temperature_app', '0017_auto_20250807_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='last_tracker_generated',
            new_name='last_generated_tracker',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='default_threshold',
        ),
        migrations.AddField(
            model_name='customer',
            name='has_global_ignore_txt',
            field=models.BooleanField(default=False, help_text='Global ignore text file uploaded'),
        ),
        migrations.AddField(
            model_name='customer',
            name='has_hc_tracker',
            field=models.BooleanField(default=False, help_text='HC Issues Tracker uploaded'),
        ),
        migrations.AddField(
            model_name='customer',
            name='has_node_coverage',
            field=models.BooleanField(default=False, help_text='Node coverage updated from TEC hosts'),
        ),
        migrations.AddField(
            model_name='customer',
            name='has_selective_ignore_xlsx',
            field=models.BooleanField(default=False, help_text='Selective ignore xlsx uploaded'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_hc_enabled',
            field=models.BooleanField(default=False, help_text='Is Health Check analysis enabled'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_hc_processing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_hc_report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='setup_status',
            field=models.CharField(choices=[('NEW', 'New Network - Needs 5 files'), ('READY', 'Ready - Needs 2 files only'), ('INCOMPLETE', 'Setup Incomplete')], default='NEW', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='tec_network_name',
            field=models.CharField(default='Unknown', help_text='Network name as appears in TEC HC system', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(help_text='Display name for the network', max_length=255),
        ),
        migrations.CreateModel(
            name='IgnoredTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case_id', models.CharField(help_text='Test case ID like 5.2.1', max_length=50)),
                ('test_description', models.CharField(blank=True, max_length=500)),
                ('ignore_type', models.CharField(choices=[('GLOBAL', 'Global - Ignore for entire network'), ('SELECTIVE', 'Selective - Ignore for specific HC IDs')], max_length=50)),
                ('hc_id', models.IntegerField(blank=True, help_text='Specific HC ID to ignore (for selective)', null=True)),
                ('priority', models.CharField(blank=True, help_text='Test priority', max_length=20)),
                ('findings', models.TextField(blank=True, help_text='Specific findings to ignore')),
                ('reason', models.TextField(blank=True, help_text='Reason for ignoring this test case')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignored_test_cases', to='Temperature_app.customer')),
            ],
            options={
                'verbose_name': 'Ignored Test Case',
                'verbose_name_plural': 'Ignored Test Cases',
                'ordering': ['test_case_id', 'hc_id'],
            },
        ),
        migrations.CreateModel(
            name='HealthCheckSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('session_type', models.CharField(choices=[('NEW_NETWORK_SETUP', 'New Network Setup (5 files)'), ('REGULAR_PROCESSING', 'Regular HC Processing (2 files)'), ('TEMPLATE_UPDATE', 'Template Files Update')], max_length=50)),
                ('report_date', models.DateField(blank=True, help_text='Date extracted from TEC report filename', null=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Processing Initiated'), ('UPLOADING', 'Files Uploading'), ('VALIDATING', 'Validating Files'), ('PROCESSING', 'Processing HC Report'), ('GENERATING', 'Generating Output'), ('COMPLETED', 'Processing Completed'), ('FAILED', 'Processing Failed'), ('CANCELLED', 'Processing Cancelled')], default='INITIATED', max_length=50)),
                ('files_expected', models.IntegerField(help_text='Number of files expected')),
                ('files_received', models.IntegerField(default=0, help_text='Number of files received')),
                ('files_processed', models.IntegerField(default=0, help_text='Number of files processed')),
                ('progress_percentage', models.IntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=255)),
                ('total_nodes_processed', models.IntegerField(blank=True, null=True)),
                ('total_test_cases_processed', models.IntegerField(blank=True, null=True)),
                ('issues_found', models.IntegerField(blank=True, null=True)),
                ('issues_ignored', models.IntegerField(blank=True, null=True)),
                ('new_nodes_discovered', models.IntegerField(blank=True, null=True)),
                ('output_tracker_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('output_tracker_path', models.CharField(blank=True, max_length=500, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_duration', models.DurationField(blank=True, null=True)),
                ('processing_log', models.TextField(blank=True, help_text='Detailed processing log')),
                ('error_messages', models.TextField(blank=True)),
                ('warnings', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hc_sessions', to='Temperature_app.customer')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Check Session',
                'verbose_name_plural': 'Health Check Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthCheckFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('HC_TRACKER', 'HC Issues Tracker'), ('GLOBAL_IGNORE_TXT', 'Global Ignore Text File'), ('SELECTIVE_IGNORE_XLSX', 'Selective Ignore Excel File'), ('TEC_REPORT', 'TEC Health Check Report'), ('INVENTORY_CSV', 'Remote Inventory CSV'), ('TEMPLATE', 'Template File')], max_length=50)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(help_text='Full path to stored file', max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'File Uploaded'), ('VALIDATED', 'File Validated'), ('PROCESSED', 'File Processed'), ('ERROR', 'Processing Error'), ('ARCHIVED', 'Archived')], default='UPLOADED', max_length=50)),
                ('processing_notes', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_current_version', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hc_files', to='Temperature_app.customer')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Check File',
                'verbose_name_plural': 'Health Check Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hc_id', models.IntegerField(help_text='Health Check ID from TEC system')),
                ('node_name', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('ne_type', models.CharField(blank=True, help_text='Network Element Type', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('site_code', models.CharField(blank=True, max_length=50)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('software_version', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_monitored', models.BooleanField(default=True, help_text='Include in HC monitoring')),
                ('first_discovered', models.DateTimeField(auto_now_add=True)),
                ('last_seen_in_report', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_coverage', to='Temperature_app.customer')),
            ],
            options={
                'verbose_name': 'Node Coverage',
                'verbose_name_plural': 'Node Coverage',
                'ordering': ['hc_id'],
                'unique_together': {('customer', 'hc_id')},
            },
        ),
    ]
