# Generated by Django 4.2.18 on 2025-08-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Temperature_app', '0018_rename_last_tracker_generated_customer_last_generated_tracker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='network_name',
            field=models.CharField(blank=True, help_text='Specific network name (e.g., East, West, North)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(help_text='Display name for the customer/organization', max_length=255),
        ),
    ]
