# Generated by Django 4.2.18 on 2025-08-07 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('network_type', models.CharField(default='Unknown', max_length=100)),
                ('setup_status', models.CharField(default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HealthCheckSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('session_type', models.CharField(choices=[('NEW_NETWORK_SETUP', 'New Network Setup'), ('REGULAR_PROCESSING', 'Regular Processing'), ('MAINTENANCE', 'Maintenance Check')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADING', 'Uploading Files'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('files_expected', models.IntegerField(default=0)),
                ('files_received', models.IntegerField(default=0)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=255)),
                ('output_tracker_filename', models.CharField(blank=True, max_length=255)),
                ('output_tracker_path', models.CharField(blank=True, max_length=500)),
                ('status_message', models.TextField(blank=True)),
                ('error_messages', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthCheck_app.customer')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hc_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NodeCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=255)),
                ('node_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='Unknown', max_length=20)),
                ('ping_status', models.BooleanField(default=False)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('services_count', models.IntegerField(default=0)),
                ('services_healthy', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthCheck_app.customer')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthCheck_app.healthchecksession')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('service_type', models.CharField(max_length=100)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='Unknown', max_length=20)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthCheck_app.nodecoverage')),
            ],
        ),
        migrations.CreateModel(
            name='HealthCheckReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_nodes', models.IntegerField(default=0)),
                ('healthy_nodes', models.IntegerField(default=0)),
                ('warning_nodes', models.IntegerField(default=0)),
                ('offline_nodes', models.IntegerField(default=0)),
                ('total_services', models.IntegerField(default=0)),
                ('healthy_services', models.IntegerField(default=0)),
                ('overall_health_score', models.FloatField(default=0.0)),
                ('report_file_path', models.CharField(blank=True, max_length=500)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HealthCheck_app.healthchecksession')),
            ],
        ),
        migrations.CreateModel(
            name='HealthCheckFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('CONFIG', 'Configuration File'), ('NETWORK_MAP', 'Network Map'), ('NODE_LIST', 'Node List'), ('SERVICE_CONFIG', 'Service Configuration'), ('BASELINE', 'Baseline Data')], max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField(default=0)),
                ('is_processed', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthCheck_app.customer')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HealthCheck_app.healthchecksession')),
            ],
        ),
    ]
