# Generated by Django 4.2.18 on 2025-08-11 09:33
# Remove HealthCheckReport model and table

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCheck_app', '0003_alter_customer_table_alter_healthcheckfile_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthCheckReport',
        ),
    ]
