# Generated by Django 4.2.18 on 2025-08-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCheck_app', '0004_auto_20250811_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='network_name',
            field=models.CharField(blank=True, help_text='Network name (e.g., East, West, North)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(help_text='Customer/Organization name (e.g., BSNL)', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='network_type',
            field=models.CharField(default='Unknown', help_text='Type of network', max_length=100),
        ),
    ]
