# Generated by Django 4.2.18 on 2025-08-26 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HealthCheck_app', '0006_alter_healthcheckfile_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_operators', models.TextField(blank=True, help_text="Comma-separated list of operators this user can access (e.g., 'BSNL,AIRTEL')")),
                ('assigned_regions', models.TextField(blank=True, help_text="Comma-separated list of regions this user can access (e.g., 'NORTH,SOUTH')")),
                ('assigned_technologies', models.TextField(blank=True, help_text="Comma-separated list of technologies this user can access (e.g., 'DWDM,MPLS')")),
                ('assigned_locations', models.TextField(blank=True, help_text="Comma-separated list of locations this user can access (e.g., 'MUMBAI,DELHI')")),
                ('is_super_user', models.BooleanField(default=False, help_text='Super users can access any region/network')),
                ('enforce_strict_validation', models.BooleanField(default=True, help_text='Enforce strict region-based validation for this user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_check_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
