# Generated by Django 4.2.18 on 2025-08-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCheck_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer Network', 'verbose_name_plural': 'Customer Networks'},
        ),
        migrations.AlterModelOptions(
            name='healthcheckfile',
            options={'verbose_name': 'Health Check File', 'verbose_name_plural': 'Health Check Files'},
        ),
        migrations.AlterModelOptions(
            name='healthcheckreport',
            options={'verbose_name': 'Health Check Report', 'verbose_name_plural': 'Health Check Reports'},
        ),
        migrations.AlterModelOptions(
            name='healthchecksession',
            options={'verbose_name': 'Health Check Session', 'verbose_name_plural': 'Health Check Sessions'},
        ),
        migrations.AlterModelOptions(
            name='nodecoverage',
            options={'verbose_name': 'Node Coverage', 'verbose_name_plural': 'Node Coverage'},
        ),
        migrations.AlterModelOptions(
            name='servicecheck',
            options={'verbose_name': 'Service Check', 'verbose_name_plural': 'Service Checks'},
        ),
        migrations.AlterField(
            model_name='healthcheckfile',
            name='file_type',
            field=models.CharField(choices=[('CONFIG', 'Configuration File'), ('NETWORK_MAP', 'Network Map'), ('NODE_LIST', 'Node List'), ('SERVICE_CONFIG', 'Service Configuration'), ('BASELINE', 'Baseline Data'), ('HC_TRACKER', 'HC Issues Tracker'), ('GLOBAL_IGNORE_TXT', 'Global Ignore Text'), ('SELECTIVE_IGNORE_XLSX', 'Selective Ignore Excel'), ('TEC_REPORT', 'TEC Health Check Report'), ('INVENTORY_CSV', 'Inventory CSV')], max_length=30),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer_networks',
        ),
        migrations.AlterModelTable(
            name='healthcheckfile',
            table='hc_files',
        ),
        migrations.AlterModelTable(
            name='healthcheckreport',
            table='hc_reports',
        ),
        migrations.AlterModelTable(
            name='healthchecksession',
            table='hc_sessions',
        ),
        migrations.AlterModelTable(
            name='nodecoverage',
            table='node_coverage',
        ),
        migrations.AlterModelTable(
            name='servicecheck',
            table='service_checks',
        ),
    ]
