# Generated by Django 4.2.18 on 2025-08-08 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCheck_app', '0002_alter_customer_options_alter_healthcheckfile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='healthcheckfile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='healthcheckreport',
            table=None,
        ),
        migrations.AlterModelTable(
            name='healthchecksession',
            table=None,
        ),
        migrations.AlterModelTable(
            name='nodecoverage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='servicecheck',
            table=None,
        ),
    ]
