# Generated by Django 4.2.18 on 2025-08-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCheck_app', '0005_customer_network_name_alter_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcheckfile',
            name='file_type',
            field=models.CharField(choices=[('CONFIG', 'Configuration File'), ('NETWORK_MAP', 'Network Map'), ('NODE_LIST', 'Node List'), ('SERVICE_CONFIG', 'Service Configuration'), ('BASELINE', 'Baseline Data'), ('HC_TRACKER', 'HC Issues Tracker'), ('TRACKER_GENERATED', 'Generated Tracker'), ('GLOBAL_IGNORE_TXT', 'Global Ignore Text'), ('SELECTIVE_IGNORE_XLSX', 'Selective Ignore Excel'), ('TEC_REPORT', 'TEC Health Check Report'), ('INVENTORY_CSV', 'Inventory CSV'), ('HOST', 'Host File')], max_length=30),
        ),
    ]
