# Generated by Django 4.2.18 on 2025-10-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCheck_app', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, help_text='Country where network is located', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='gtac',
            field=models.CharField(blank=True, help_text='Global Technical Assistance Center', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='monthly_runs',
            field=models.JSONField(blank=True, default=dict, help_text='Monthly health check run dates'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ne_type',
            field=models.CharField(blank=True, help_text='Network Element type (e.g., 1830 PSS)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='node_qty',
            field=models.IntegerField(default=0, help_text='Number of nodes in network'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_runs',
            field=models.IntegerField(default=0, help_text='Total number of health check runs'),
        ),
    ]
